0.1.734

diff --git a/support/btle b/support/btle
--- a/support/btle
+++ b/support/btle
@@ -68,7 +68,7 @@ btle_packet_processor () {
 	local should_ignore
 
 	#POPULATE PACKET 
-	packet=$(echo "$1" | sed 's/> *//g;s/[^0-9A-Z ]//g')
+	packet=$(echo "$1" | sed 's/> *//g;s/[^0-9A-F ]//g')
 
 	#BEACON PACKET?
 	if [[ $packet =~ ^04\ 3E\ 2A\ 02\ 01\ .{26}\ 02\ 01\ .{14}\ 02\ 15 ]]; then
@@ -174,7 +174,7 @@ btle_packet_processor () {
 		return 0	
 	fi
 
-	(>&2 echo "error 2: rejecting packet $packet")
+	(>&2 echo "error 2: rejecting packet [$packet]")
 }
 
 # ----------------------------------------------------------------------------------------
