0.1.851
• Attempt to prevent broken pipe

diff --git a/support/btle b/support/btle
--- a/support/btle
+++ b/support/btle
@@ -229,8 +229,7 @@ btle_text_listener () {
 			if [[ $line =~ ^\> ]] || [[ $line =~ ^\< ]] || [[ $line =~ RSSI ]]; then
 				[[ $line =~ RSSI ]] && packet="$packet|$line"
 				if [[ $packet =~ ^\> ]]; then 
-					printf "%s\n" "1$packet" > packet_pipe & 
-					disown "$!"
+					printf "%s\n" "1$packet" > packet_pipe
 				fi 
 				packet=""
 				packet=$line
@@ -262,8 +261,7 @@ btle_listener () {
 			if [[ $line =~ ^\> ]] || [[ $line =~ ^\< ]]; then
 				# process the completed packet (unless this is the first time through)
 				if [ "$packet" ] && [[ $packet =~ ^\> ]]; then
-					printf "%s\n" "0$packet" > packet_pipe & 
-					disown "$!"
+					printf "%s\n" "0$packet" > packet_pipe
 				fi
 				# start the new packet
 				packet=$line
@@ -279,9 +277,7 @@ btle_listener () {
 
 				#PROCESS A PACKET WHEN IT IS COMPLETE
 				if [ "$complete_packet_str_length" == "${#packet}" ]; then 
-					printf "%s\n" "0$packet" > packet_pipe & 
-					disown "$!"
-
+					printf "%s\n" "0$packet" > packet_pipe
 					packet=""
 				fi 
 			fi
@@ -326,6 +322,6 @@ btle_packet_listener () {
 	done
 
 	#REPORT ERROR
-	(>&2 echo "error! irrecoverable btle_scanner error")
+	(>&2 echo "error! irrecoverable btle_packet_listener error")
 }
 
