0.1.465

diff --git a/support/setup b/support/setup
--- a/support/setup
+++ b/support/setup
@@ -46,13 +46,11 @@ MQTT_CONFIG="$base_directory/mqtt_preferences"
 if [ -f $MQTT_CONFIG ] ; then 
 	source $MQTT_CONFIG
 
-	echo "Testing: $mqtt_certificate_path"
-
 	#ERRORS
 	[ "$mqtt_address" == "0.0.0.0" ] && echo "Error: Please customize mqtt broker address in: mqtt_preferences" && should_exit=true
 	[ "$mqtt_user" == "username" ] && echo "Error: Please customize mqtt username in: mqtt_preferences" && should_exit=true
 	[ "$mqtt_password" == "password" ] && echo "Error: Please customize mqtt password in: mqtt_preferences" && should_exit=true
-	[ -f "$mqtt_certificate_path" ] && [ ! -z "$mqtt_certificate_path" ] && echo "Error: Please check mqtt certificate path in mqtt_preferences" && should_exit=true
+	[ ! -f "$mqtt_certificate_path" ] && [ ! -z "$mqtt_certificate_path" ] && echo "Error: Please check mqtt certificate path in mqtt_preferences" && should_exit=true
 
 	#WARNINGS
 	[ -z "$mqtt_port" ] && echo "Warning: Variable mqtt_port does not appear in: mqtt_preferences. Using default port 1883". && mqtt_port="1883"
@@ -164,10 +162,16 @@ WantedBy=multi-user.target network.target" > "$service_path"
 	sudo systemctl enable monitor.service
 fi 
 
+#----------------------------------------------------------------------------------------
+# BEFORE WE ECHO PREFERENCES, EXIT IF WE NEED TO 
+# ----------------------------------------------------------------------------------------
+
+#ARE REQUIREMENTS MET? 
+[ "$should_exit" == true ] && exit 1
 
 #----------------------------------------------------------------------------------------
 # CHECK BEHAVIOR CONFIGURATION FILES
-# ----------------------------------------------------------------------------------------
+#----------------------------------------------------------------------------------------
 
 #MQTT PREFERENCES
 PREF_CONFIG="$base_directory/behavior_preferences"
